version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing TruffleHog..."
      - pip install trufflehog3
      
  pre_build:
    commands:
      - echo "Starting secret scan..."
      - echo "Build started on `date`"
      
  build:
    commands:
      - echo "Scanning repository for secrets..."
      - trufflehog3 --format json --output secrets-report.json ./ || echo "Scan completed"
      - |
        echo "Debug: Checking secrets-report.json..."
        if [ -f secrets-report.json ]; then
          echo "File exists. Content:"
          cat secrets-report.json
          echo "End of file content."
          CONTENT=$(cat secrets-report.json | tr -d '\n\r\t ')
          echo "Cleaned content: '$CONTENT'"
          if [ "$CONTENT" != "[]" ] && [ "$CONTENT" != "" ]; then
            echo "🚨 SECRETS DETECTED! Build failed."
            exit 1
          else
            echo "✅ No secrets detected. Build passed."
          fi
        else
          echo "✅ No secrets report file. Build passed."
        fi
        
  post_build:
    commands:
      - echo "Secret scan completed on `date`"

artifacts:
  files:
    - secrets-report.json
  name: secret-scan-results